My Utils
========

Under package io.endeios

*Utils*
-------

Useful Static imports, featuring

### inFx

simeple closure wrapped inside the Platform.runLater idiom

[source,groovy]
----
import static io.endeios.Utils

...(in non groovyfx thread)
inFX{
    label.text = "Hello!"
    }

----



*XMLRPCClient*
--------------

Simple wrap for apache's xmlrpcclient library

[source,groovy]
---- 
import io.endeios.XMLRPCClient
def serverProxy = new XMLRPCClient(new URL('http://rpc.example.com:8000/RPC2'))
//then simply "call methods"
serverProxy.system.listMethods().each{println it}
// let' say that there is the usual sum(integer integer) method
def sum = serverProxy.sum(41,1)
----

*DirectoryNotifier*
-------------------

Notifies to an Observer when there is a change in a file of a given directory

[source,groovy]
----
import java.nio.file.*
import io.endeios.DirectoryNotifier

def fs = FileSystems.getDefault()
def path = fs.getPath('.')

def dn = new DirectoryNotifier(path)
println dn
def observer = new myObserver()
dn.addObserver(observer)
def th = new Thread(dn,"notifierThread")
println th
th.setDaemon(false)
th.start()




class myObserver implements Observer{
    public void update(Observable obs, Object obj){
        if(obs instanceof DirectoryNotifier ){
            println "File ${obj.file} has been updated with ${obj.data}"
        }
    }
}
----

*ObservableTimer*
----------------

Simple Timer that ticks on a javafx thread, and sends notify events at the given interval

[source,groovy]
----
import io.endeios.ObservableTimer
def ticker = new ObservableTimer(time)

...(in a controller, implementing Observer, for a javafx panel)

public void update(Observable obs, Object obj){
    refresh()//refresh polling routine 
}


----

* GroovyResultValueFactory and ListResultValueFactory *
------------------------------------------------------

Adapter classes to help in laying out tables in groovyfx
contests
- GroovyResultValueFactory for those times in wich you need to use
groovy's Sql

- ListResultValueFactory for those times in wich you need to lay out lines of strings

see src/main/GroovyFxExamples.groovy

* WindowsRegistry *
-------------------

Windows Register utility reader
Shamelessly uses the reg utility under windows
[source,groovy]
----
import io.endeios.WindowsRegistry

def vlcInstallDir = WindowsRegistry.readRegistry("HKEY_LOCAL_MACHINE\\SOFTWARE\\VideoLAN\\VLC","InstallDir")

println vlcInstallDir

----
